### ISSUE TITLE
Scenario tutorial uses outdated code

### ISSUE THREAD

**Issue by qrilka** [machinezone/mzbench#100]
`doc/scenarios/tutorial.md` sets up target webserver as
```
    set_host("localhost")
    set_port(8080)
```
But in `workers/http/examples/localhost.bdl` I see
```
connect("localhost", 8080)
```

**Comment by parsifal-47** [comment]
Fixed,
thanks for reporting this!

**Comment by qrilka** [comment]
@parsifal-47 side question - I haven't found a way to pass headers to `http_worker` but as I just wanted to disable keepalive using `set_options(connection = close)` seem to work and connect/disconnect as in `keepalive.bdl` in examples does not seem to prevent keepalive (though I didn't dig deeper yet)

**Comment by parsifal-47** [comment]
Not sure if I got your question,
`set_options` should be the method you looking for, it sets headers for http request.
In `keepalive.bdl` example clients are reconnected with `disconnect` and `connect` method.

Do you need server to close connection after each request?
Does it look like headers are not passing to HTTP request?

**Comment by qrilka** [comment]
@parsifal-47 I was using connect/disconnect approach from `keepalive.bdl` and it didn't result in connection being closed - keepalive get's used by default and I saw connection being reused in tcpdump. I guess hackney moves that connection back to the pool  on `close`(though I didn't check that running Erlang code myself)

**Comment by parsifal-47** [comment]
thanks, now I got it, I'll check that tomorrow

**Comment by qrilka** [comment]
thanks, otherwise feel free to close this ticket @parsifal-47 :)

**Comment by parsifal-47** [comment]
I've disabled dynamic connection sharing, it is in master and checked with `tcpdump`

Thanks again for reporting this!
