### ISSUE TITLE
AMI for `eu-west-2`

### ISSUE THREAD

**Issue by gdhgdhgdh** [machinezone/mzbench#102]
Hello - I was pleased to see that there's a range of prefabbed AMI's for many regions. Can I request that `eu-west-2` be added to the list? My environments are all in that region and I'd like the benchmarking to be as local as possible to the target without being `localhost` :)

Perhaps if you're using Packer you could publish the `build.json` so we can easily build our own AMI's and hence avoid the hit and miss approach of a list of requirements in English?

Cheers,
Gavin.

**Comment by parsifal-47** [comment]
Hello,
I have copied this image to eu-west-2, id is: ami-e2c3d686,
unfortunately, we don't use packer, but we have the following description for image software:
`images must have Erlang R17+, gcc, gcc-c++, git, and sudo installed. Sudo must be available for non-tty execution; put Defaults !requiretty in /etc/sudoers. The SSH and TCP ports 4801-4804 must be open; MZBench uses them internally to send logs and metrics data from nodes to the server.`

Published here: https://github.com/machinezone/mzbench/blob/master/doc/cloud_plugins.md

Thanks for your interest

**Comment by gdhgdhgdh** [comment]
Thank you :)
