### ISSUE TITLE
init.d script /systemd unit file for RPM

### ISSUE THREAD

**Issue by gdhgdhgdh** [machinezone/mzbench#103]
On the packaged RPM version of 0.5.1, https://machinezone.github.io/mzbench/deployment/ suggests to run `mzbench start_server` however this fails because the `mzbench` binary is provided by the `mzbench_api_client` Python library and there is no `start_server` option available.

I had to `/opt/mzbench_api/bin/mzbench_api start` - could this be mentioned in the docs (or ideally a systemd unit file be included in the RPM ?)

**Comment by parsifal-47** [comment]
I don't recommend this way of starting the server, it could miss some of mandatory ENVs,
I'll check and update current pip packet, it should be possible to use start_server when you have it from RPM

**Comment by parsifal-47** [comment]
done, please update pip packet and check your issue

Thank you!

**Comment by gdhgdhgdh** [comment]
Cool, I'm glad I brought it up. New pip packet is downloaded and working fine with `mzbench start_server` :) Thanks for the super-fast response!
