### ISSUE TITLE
Iterator problem

### ISSUE THREAD

**Issue by gliush** [machinezone/mzbench#107]
Hi.

I have the following scenario:

```
#!benchDL
make_install(git=<myrepo>, branch=<mybranch>, dir=".")
defaults("pool_size" = 1)
defaults("usage_max" = 10)
defaults("idx_max" = 10000000000) # 10^10

pool(size = var("pool_size"), # one execution "thread"
     worker_type = myworker):

        set_host("http://172.17.2.72:8080/v1/batch/masks")
        loop(time = 100 sec, # total loop time
             rate = 10 rps,
             iterator = "i"): # 10 rps for every worker
            dump(sprintf("idx: ~p, random: ~p”, [numvar("i"), random_number(1, numvar("usage_max"))]))
            create_use_delete(random_number(1, numvar("usage_max")), numvar("i"))
            print("done")
```

And I see in the log the following:
```
15:05:08.632 [info] <0.267.0> Idx=253, UsageNum=7
15:05:08.949 [info] <0.267.0> notify latency: 43
15:05:08.949 [info] <0.267.0> Scenario print: "done"
15:05:08.949 [info] <0.267.0> "idx: 254, random: 8"
15:05:08.949 [info] <0.267.0> Idx=254, UsageNum=9
15:05:08.994 [info] <0.267.0> notify latency: 44
15:05:09.284 [info] <0.267.0> notify latency: 43
15:05:09.284 [info] <0.267.0> Scenario print: "done"
15:05:09.336 [info] <0.267.0> "idx: 606.31, random: 4"
15:05:09.336 [info] <0.267.0> Idx=606.31, UsageNum=8
```

I.e. I have the following iterator values:
```
Idx=253
…
Idx=254
…
Idx=606.31
```
So, it becomes very large and becomes float!

It happens only if I have a large worker, I couldn't shrink the test to the small one, sorry.

Ivan.

**Comment by parsifal-47** [comment]
Sorry for delay,
Thanks a lot for finding and reporting this issue, should be fixed in master with https://github.com/machinezone/mzbench/commit/a4a23c3897ce2fe7850163989d175334e573fc7b

Do you need an RPM with this fix?

**Comment by gliush** [comment]
Nope, I don't.
Thank you for your work!

**Comment by timofey-barmin** [comment]
@parsifal-47 simple rounding will not fix this issue. Iterator will still jump like: 1,2,3, 100, 101, 102, 50, 51 ....
 We need to have separate counter for iterator in the loop function.

**Comment by parsifal-47** [comment]
I'm not sure about it, if you are referring to parallel execution, they will never be sorted, the same for worker start. Ordering here couldn't be strict because it is a bottleneck.

Or is it about dynamic-env-update?

**Comment by timofey-barmin** [comment]
there are two things that will change the counter:
1) dynamic env update
2) periodical counter corrections in case if the real rate is lower than desirable

**Comment by parsifal-47** [comment]
yes, that was right.
Sorry, it took me a while to get to this issue.
It is fixed now with separate counter. I have also created "Iterator checker" in a separate branch https://github.com/machinezone/mzbench/commit/37b4c2a2d2c08c3a238b3c9b745de9aa5597d170
to make sure it behaves properly on env updates and periodical counter corrections.

Thanks for finding and reporting this issue!

**Comment by parsifal-47** [comment]
Feel free to reopen this issue any time you need
