### ISSUE TITLE
Server has failed to start, error file is empty

### ISSUE THREAD

**Issue by steffenix** [machinezone/mzbench#108]
Following: https://machinezone.github.io/mzbench/#installation
Server has failed to start, timeout
Check ..../mzbench/bin/../server/log/error.log for details

cat server/log/error.log
The file is empty.

I am using the latest version pulled from github on the latest mac OS X with OTP 19.

**Comment by parsifal-47** [comment]
Hi,
that's interesting, looks like logs are somewhere else, please try to run
`./server/_build/default/rel/mzbench_api/bin/mzbench_api console`
from your mzbench source root folder and provide me the output (it should be some error message at the end)

**Comment by steffenix** [comment]
Hey,
So using your command the server starts.

**Comment by parsifal-47** [comment]
Unfortunately, it does not explain much. It could mean some problem disappeared, for example port is now free or you have some free space on your disk.
"console" mode couldn't be used for normal operation because some ENVs are missing.

My current suggestion is to stop it and try to restart with `mzbench start_server`

**Comment by steffenix** [comment]
Yeah this was my thought too but the only process that could hold ports is docker and I made sure it was off before opening the issue. I can start it with the console mode but not `mzbench start_server` still does not get an message in the error file but some process are started 


```
21772 ??         0:00.14 /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/erts-8.2.2/bin/epmd -daemon
21779 ??         0:00.00 /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/erts-8.2.2/bin/run_erl -daemon /tmp/erl_pipes/mzbench_api/ /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/log exec "/Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/bin/mzbench_api" "console"
21824 ??         0:00.00 /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/lib/os_mon-2.4.1/priv/bin/cpu_sup
21780 ttys002    0:14.21 /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/erts-8.2.2/bin/beam.smp -- -root /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api -progname Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/bin/mzbench_api -- -home /Users/steffenix -- -boot /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/releases/0.5.1/mzbench_api -mode interactive -boot_var ERTS_LIB_DIR /Users/Repos/mzbench/server/_build/default/rel/mzbench_api/erts-8.2.2/../lib -config /Users/steffenix/Repos/mzbench/server/_build/default/rel/mzbench_api/releases/0.5.1/sys.config -sname mzbench_api -setcookie mzbench_api -heart -- console
```

**Comment by parsifal-47** [comment]
If you have Docker, you could try to use mzbench docker container to start it:

`docker run -d -p 4800:80 --name mzbench_server docker.io/ridrisov/mzbench`

unfortunately it does not answer original question, could you make: `ls -la server/log/` to check that something is written there during its startup?

**Comment by parsifal-47** [comment]
does this docker container work for you?

**Comment by steffenix** [comment]
I haven't look back.
