### ISSUE TITLE
sending stats to a graphite server

### ISSUE THREAD

**Issue by benoitc** [machinezone/mzbench#109]
The diagram in the overview let think it's possible to send the data directly to graphite (which is a thing we need to do). Is this possible actually? Where should I look to add a simple support for it?

**Comment by parsifal-47** [comment]
that is probably an outdated information, please send us a link to it,
graphite was used at our dashboard for graphics, now we use https://www.metricsgraphicsjs.org/
raw data is available at "data" endpoint or with CLI:
```
mzbench [--host=<host>] [--no_cert_check] data [(--target=<name>...)] [--format=(csv|json)] <bench_id>
```
json format here is graphite-compatible

**Comment by benoitc** [comment]
This is the overview page, latest diagram: https://machinezone.github.io/mzbench/

<img width="470" alt="scheme_2" src="https://cloud.githubusercontent.com/assets/14498/25128682/d21f17aa-243a-11e7-8383-d35ad4a08ebd.png">

Are you suggesting to export them to grafana after a bench? What do you do with the data of the service on which the benchmark is executed? [Importing metrics](https://machinezone.github.io/mzbench/workers/#importing-external-metrics)?

**Comment by parsifal-47** [comment]
yes, for example, the data is aggregated in a same way with normal metrics (counters are addable),
thanks for reporting this!

**Comment by benoitc** [comment]
@parsifal-47 thanks for the suggestion :) I will let you close the issue since it probably require a change in the doc :)

**Comment by parsifal-47** [comment]
doc updated, thanks!
