### ISSUE TITLE
What do I need to install on the machines that will be used as worker nodes?

### ISSUE THREAD

**Issue by dii14** [machinezone/mzbench#112]
I am using a static cluster of two machines(Ubuntu 16), they both have Erlang and the sample example that prints foo works. However, when I use a function like random_binary I get the following error:
`14:05:56.853 [error] <0.235.0> Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /home/ubuntu/.local/share/mzbench/lib/crypto-3.6.1/priv/lib/crypto: 'libcrypto.so.10: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.`
I do have openssl installed.

Any ideas? Thanks

**Comment by timofey-barmin** [comment]
Hey, looks like you have erlang without crypto lib. You can check it by calling any crypto function, like:
```
$ erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> crypto:version().
"3.6.3"
```

**Comment by dii14** [comment]
Well not really. I did that and I do have crypto installed. The problem is that on ubuntu 16 the lib is called libcrypto.so.1.1.0 instead of libcrypto.so.10. So as learned on other threads I setup a symlink from my .so.1.1.0 to .so.10 but then the versions are not right. I dont have access to my laptop now but I will let you know of more details on tuesday. Thanks for helping out.
