### ISSUE TITLE
Use Elixir as a scripting language

### ISSUE THREAD

**Issue by aidylewis** [machinezone/mzbench#118]
1. The DSL is ugly and clunky and you'd hit issues with non-trivial tasks.
2. You'd gain more traction

**Comment by parsifal-47** [comment]
The main reason for DSL is competency level isolation, using existing language doesn't solve this, to attract some attention we could use Whitespace as our input language, make some conference appearances with it etc. But it does not solve any business cases.

Btw, you could use subset of Erlang as input and also Elixir if you know how to convert between them :)

**Comment by aidylewis** [comment]
Lets say I wanted to write percentiles to stdout. Would your DSL allow this?

**Comment by aidylewis** [comment]
The DSL looks extensible. Please acccept my apologies. BTW, I am a load tester for the BBC and looking for something open-source and which I can extend. I am also interested in functional programming and increasingly Erlang. Our current paid for tool does not support HTTP/2 (meaning hundreds of our tests will be inaccurate and therefore useless (fall back to HTTP 1.1).

**Comment by aidylewis** [comment]
The DSL looks extensible. Please acccept my apologies. BTW, I am a load tester for the BBC and looking for something open-source and which I can extend. I am also interested in functional programming and increasingly Erlang. Our current paid for tool does not support HTTP/2 (meaning hundreds of our tests will be inaccurate and therefore useless (fall back to HTTP 1.1)).

**Comment by parsifal-47** [comment]
glad to hear, any feedback is interesting, if
https://github.com/ninenines/gun
or
https://github.com/joedevivo/chatterbox
have good support for HTTP/2 it shouldn't be hard to integrate to MZBench
