### ISSUE TITLE
Provide Local Install / Execution Options

### ISSUE THREAD

**Issue by pulltab** [machinezone/mzbench#2]
While requiring sudo access is tolerable (not ideal in general) on my local laptop, as a user I don't necessarily have sudo access on the sorts of machines I would like to run by benchmarks on.

Installing / running the server shouldn't require sudo privs.

**Comment by parsifal-47** [comment]
We have removed sudo requirement by putting MZBench node to user home dir.

**Comment by parsifal-47** [comment]
Correction: we still require sudo for server installation, but do not require sudo for server running and node installation/running.

Anyway, we'll fix that and let you know, thank you!

**Comment by parsifal-47** [comment]
MZBench server does not require sudo anymore, because it does not require installation at all. Now you may require root privileges to run server at 80 port, but default port is 4800. Thanks.
