### ISSUE TITLE
Packages for Server

### ISSUE THREAD

**Issue by uprial** [machinezone/mzbench#24]
Hi guys,

It would be great to have some kind of packages for the most popular operation systems: RPM and DEB.
It isn't easy to understand what version of C++ to install and how to do it.
It's easier with Python and PIP because they are in the most systems by default.
But I should think again how to install the Erlang version you need.

Additionally it would be great to have by default at least working config in
 /etc/mzbench/server.config

So, I just need a possibility to install a package and enjoy having a server.

**Comment by merlin86** [comment]
Hi!

> It would be great to have some kind of packages for the most popular operation systems: RPM and DEB.

Thanks for the idea! We will create a ticket and do it when we are over with our current priorities.

> It isn't easy to understand what version of C++ to install and how to do it.

Are you asking about what C++ compiler to use? It is needed by HDR Histogram. You can use any reasonably modern version of GCC or Clang.

> It's easier with Python and PIP because they are in the most systems by default.

Well, C++ compiler is also installed on most systems by default.

> But I should think again how to install the Erlang version you need.

You can download the package for you favorite OS or distribution from [Erlang Solutions](https://www.erlang-solutions.com/resources/download.html).

> Additionally it would be great to have by default at least working config in
/etc/mzbench/server.config

You don't need it. If you launch the server without config, it will use a working reasonable defaults.

If you want to see an example of a configuration file, look at [server/server.config.example](https://github.com/machinezone/mzbench/blob/master/server/server.config.example).

**Comment by uprial** [comment]
> Thanks for the idea! We will create a ticket and do it when we are over with our current priorities.
We've figured out how to do it right now. So, it isn't critical. Just an improvement request.
Thank you for accepting that request!

> Are you asking about what C++ compiler to use? It is needed by HDR Histogram. You can use any reasonably modern version of GCC or Clang.
It would be great to know a minimal version number from the documentation. Or just don't care about it if I use DEB/RPM.

> Well, C++ compiler is also installed on most systems by default.
My CentOS6.5 hadn't it

> You don't need it. If you launch the server without config, it will use a working reasonable defaults.
But what defaults?
It would be much more convenient to have an existing file with all the configuration parameters were set to default. So I don't need to go deep into documentation to change a configuration in the file.
> If you want to see an example of a configuration file, look at server/server.config.example.
Ok, I've got it.

Thank you for responding!

**Comment by parsifal-47** [comment]
We finally have no-deps RPM with MZBench for CentOS and Amazon linux,
use [github releases page](https://github.com/machinezone/mzbench/releases) to download
