### ISSUE TITLE
Install a server and a worker in an isolated environment

### ISSUE THREAD

**Issue by uprial** [machinezone/mzbench#25]
Hi guys,

it would be great to don't mess my current environment by your Erlang's version.
I usually work with Erlang v18. So I can't have your server and worker at the same node. :(
And moreover I have Python3+ there.

What about to have a virtual environment for your Python dependencies and Erlang-release for the others?
Together with my request https://github.com/machinezone/mzbench/issues/24 it will help to avoid of installing C++ compiler.

**Comment by merlin86** [comment]
Hi!

> I usually work with Erlang v18. So I can't have your server and worker at the same node. :(

MZBench works with Erlang 18, see our [Travis](https://travis-ci.org/machinezone/mzbench).

> And moreover I have Python3+ there.

I have 3 different versions of Python installed on at the same time on my Mac. Why can't you do the same?

> What about to have a virtual environment for your Python dependencies and Erlang-release for the others?

For Python dependencies you can use [VirtualEnv](https://virtualenv.readthedocs.org/en/latest/).

Do I understand correctly that you want us to provide you with a Vagrant file or VirtualBox virtual machine image with MZBench pre-installed? If this is the case, we can probably do that.

**Comment by uprial** [comment]
> MZBench works with Erlang 18, see our Travis.

Ok, thank you. It wasn't obvious because you require 'Erlang R17' in your documentation.

> I have 3 different versions of Python installed on at the same time on my Mac. Why can't you do the same?

Unfortunately my `#!/usr/bin/env python` returns a Python dramatically incompatible with Python-2.{6,7}
Your requirement force me to install a Python2.6 that will override my already installed Python that I love and it will break randomly already installed software.

> For Python dependencies you can use VirtualEnv.
> Do I understand correctly that you want us to provide you with a Vagrant file or VirtualBox virtual machine image with MZBench pre-installed? If this is the case, we can probably do that.

Yes, of course I can use VirtualEnv. But what about Erlang? I would like to not mess my system with other versions of Erlang, Python, C++ or whatever else what I don't really need.

One button what installs all the infrastructure and don't mess my global environment except of current directory would be the best solution.
It could be an RPM/DEB package with Erlang release, Python Virtual Env and already compiled by C++ binaries. Or a Vagrantfile. Or maybe something else.

BTW, this issue isn't critical for me right now. It just took some time for me to create an environment to use your product.

**Comment by parsifal-47** [comment]
as we have [Docker image for MZBench](https://github.com/machinezone/mzbench#from-docker-container), issue could be closed, feel free to reopen it if you need to
