### ISSUE TITLE
Tutorial about a custom worker

### ISSUE THREAD

**Issue by uprial** [machinezone/mzbench#26]
Hi guys,

one day I needed a benchmark framework with a possibility to write as custom workers as it possible.
I compared several solutions like tsung and so on. Additionally to features list my second question was "is it easy to use this framework?" So, I spent several hours in creating my custom worker to figure out how it is going.
It would be great to have a simple tutorial about "how to use my own worker from scratch" because it seems to be the core kill-feature in comparison with other solutions.

**Comment by merlin86** [comment]
Hi!

Can you explain why [doc/workers.md](https://github.com/machinezone/mzbench/blob/master/doc/workers.md) doesn't suit you needs? It seems do be exactly what you want.

**Comment by uprial** [comment]
It helps very well now, when I've already decided to use MZBench. You have great API Reference guys!

But it almost frightened my off from MZBench when I was choosing which framework to use. Because there isn't a tutorial of how to create a custom worker from scratch as fast as it possible. To make a decision how painful in general it is.

Again, this is an improvement request based on my experience, not a critical issue.
And thank you for such fast response!

**Comment by moigagoo** [comment]
@uprial Here's an updated version of the custom worker tutorial: http://machinezone.github.io/mzbench/workers/#how-to-write-a-worker

**Comment by uprial** [comment]
@moigagoo, thank you!

**Comment by uprial** [comment]
@moigagoo, I've read your fix.
But about something completely different. :) How about to list a core feature 'completely custom workers' with integration cost and requirements? And moreover you can list the most useful cases and describe how convenient it will be done.
Right now there is a list of API references and installation instructions, but a first question is: what real problems I can solve with your nice product? In comparison with competitors' products.

**Comment by moigagoo** [comment]
@uprial Could you please suggest a real-life example we could base a tutorial on? Like, load-test Google with HTTP GET requests, but something that would actually require a custom worker?

It seems like creating a worker for a popular service like Twitter would make a useful and informative tutorial, don't you think?

**Comment by parsifal-47** [comment]
I think we could close this one,
we have a tutorial here: https://github.com/machinezone/mzbench/blob/master/doc/scenarios/tutorial.md

Please feel free to re-open this issue or create new one if needed,
thank you!
