### ISSUE TITLE
Turn off one of the counter graphs

### ISSUE THREAD

**Issue by lukyanov** [machinezone/mzbench#30]
Any counter now draws two graphs in the dashboard: absolute and rps. For the most metrics only one or another is usually needed, but rarely both. It would be great if I could specify what type I need explicitly or turn off one of the graphs.

**Comment by timofey-barmin** [comment]
done

There are two new options in metric opts:
  visibility :: true | false, % true by default
  rps_visibility :: true | false % by default is set to visibility option value

Please check it out.

Example:

```
metrics() ->
  [{"print", counter, #{visibility => false, rps_visibility => true}}]
```

**Comment by lukyanov** [comment]
Thank you!
