### ISSUE TITLE
Stale Erlang nodes on workers

### ISSUE THREAD

**Issue by lukyanov** [machinezone/mzbench#32]
When I run a scenario on specific nodes (I allocate them by myself), sometimes due to some abnormal termination of the test I run into the following situation: worker nodes keep some Erlang code running and when a new test starts it can not provision workers because there is already something there. Usually such a new test times out when in the provisioning stage.
In order to start the test I need to ssh to each worker node and kill Erlang processes there.

**Comment by lukyanov** [comment]
I think it would useful if MZ Bench controller cleans up the worker nodes before provisioning them.

**Comment by timofey-barmin** [comment]
We are calling 'mzbench/bin/mzbench stop' before every provisioning actually. It's a bit odd it doesn't work in your case.
I have an idea about some kind of watchdog to run on the worker nodes: if worker node has been disconnected for the server for several minutes(or seconds) it stops itself.

**Comment by lukyanov** [comment]
I think I found one of the possible reasons when it happens. It happens when I accidentally run a new bench before stopping the previous one. In this case the new run will not work which is expected, but then, even after I stop the old run, the new one still doesn't work with the error:
```
11:50:06.745 [error] [ API ] [ EXEC ] Command execution failed in 31378.307 ms
Cmd: ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@172.31.196.170 "source /etc/profile; ~/.local/share/mzbench/bin/wait_cluster_start.escript 30000 mzb_director47@ip-172-31-196-170 mzb_worker47@ip-172-31-196-90 mzb_worker47@ip-172-31-196-181 mzb_worker47@ip-172-31-196-248 mzb_worker47@ip-172-31-196-174 mzb_worker47@ip-172-31-196-219 mzb_worker47@ip-172-31-196-64 mzb_worker47@ip-172-31-196-233"
Exit code: 1
Output: Warning: Permanently added '172.31.196.170' (ECDSA) to the list of known hosts.
{1452,685776,108109} starting
{1452,685776,243878} hostnames are resolvable
{1452,685776,310531} hostnames are reachable
unexpected stop: timeout
{"init terminating in do_boot",timeout}

Crash dump was written to: erl_crash.dump
init terminating in do_boot (timeout)

11:50:06.746 [error] [ API ] Stage 'pipeline - provisioning': failed
Command returned 1:
 ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@172.31.196.170 "source /etc/profile; ~/.local/share/mzbench/bin/wait_cluster_start.escript 30000 mzb_director47@ip-172-31-196-170 mzb_worker47@ip-172-31-196-90 mzb_worker47@ip-172-31-196-181 mzb_worker47@ip-172-31-196-248 mzb_worker47@ip-172-31-196-174 mzb_worker47@ip-172-31-196-219 mzb_worker47@ip-172-31-196-64 mzb_worker47@ip-172-31-196-233"
Command output: Warning: Permanently added '172.31.196.170' (ECDSA) to the list of known hosts.
{1452,685776,108109} starting
{1452,685776,243878} hostnames are resolvable
{1452,685776,310531} hostnames are reachable
unexpected stop: timeout
{"init terminating in do_boot",timeout}
```

**Comment by timofey-barmin** [comment]
Yep, that looks weird. I'm gonna push some changes to fix it in a day or two.
