### ISSUE TITLE
Tried to copy ami-3b90a80b into my region: You do not have permission to access the storage of this ami

### ISSUE THREAD

**Issue by MaxDaten** [machinezone/mzbench#35]
I'm currently fiddling a bit around with mzbench, and I'm very impressed. After taking some hurdles it is super easy to adjust the http_worker to my needs. I hope I can provide a PR or an release of my extended http woker (including hackey header and options).

But now to the reason of this issue: I tried to copy your ami to my region (`eu-central-1`), but it seems you granted no read access to your ami bucket. Can you adjust it or copy it for me into the region? I would appreciate it :)

Greetings and thanks to open source this handy tool.

**Comment by parsifal-47** [comment]
Nice to hear!

ami for eu-central-1 is ami-dfd6c8b3, please check if it works for you

**Comment by MaxDaten** [comment]
Sorry for the late answer,

I want to thank you, everything is fine.

Greetings

**Comment by parsifal-47** [comment]
Nice to hear that!
