### ISSUE TITLE
Problems with the unnderstanding of the work distribution in a distributed bench

### ISSUE THREAD

**Issue by MaxDaten** [machinezone/mzbench#36]
Hi,

yesterday I was able to my scenario on aws-ec2, but I have problems to understand the work distribution. My Scenario is as simple as this:

```erlang
[
    % GET pool
    { pool,
       [ {size, {numvar, "conn_count", 10}},
         {worker_type, http_worker}
       ],

       [
           { set_host, {var, "host"} },
           { set_port, {numvar, "port", 80} },

           % Get User
           { loop,
               [ {time, {{numvar, "time_minutes", 5}, min}},
                 {rate, {ramp, linear, {1, rps}, {{numvar, "max_rps", 10}, rps}}}
               ],
               [

                 % get a user
                 { get, "/user/id123"}
               ]
           }
       ]
    }
].
```

But executing this with default values for `conn_count`, `max_rps`, `time_minutes` on 5 nodes I would expect similar behavior as in a local single node execution. The rps value would scale from 10 to 1000 (or cap at a limit of the host): 10 jobs of the pool, each with an increasing rate from 1 to 10 over 5 minutes.

But this is the rps graph generated from a distributed execution on 5 nodes:

![screenshot 2016-01-05 23 14 41](https://cloud.githubusercontent.com/assets/1087418/12130806/e01bb08c-b40d-11e5-8825-376ea080c5a4.png)

This is the graph with same settings but one local (dummy) node:

![screenshot 2016-01-06 00 45 58](https://cloud.githubusercontent.com/assets/1087418/12131034/8ddd350a-b40f-11e5-95bf-6623fd651816.png)

Why is the distributed rps so much lower with the same settings? How should I interpret the pool size? Possible as a unit to simulate individual clients? Why behaves the pool so differently when distributed? I think I have a fundamental misunderstanding about the distribution model. Can you help me out?

Greeting

**Comment by timofey-barmin** [comment]
Hi,
thank you for writing
As far as I see your understanding of the distribution mode is pretty much the same as ours:)
Yes it's odd that you have different pictures for this scenario.

1) Actually, both graphs look odd to me. If you run the script with default var values you should see a ramp from 10 to 100 (10x1 to 10x10) rps, but I see 250rps on your second graph. Look what I have on localhost for your script with default settings: 
<img width="439" alt="screen shot 2016-01-06 at 12 32 30" src="https://cloud.githubusercontent.com/assets/3727395/12136460/bb209188-b469-11e5-9572-082811807394.png">

2) What do you see on latency graphs? may be when you move to ec2 latencies grow. If one request takes 100ms for example you will not be able to generate more than 10 rps sending requests one after another. In this case you can either send them in parallel (see parallel option for loop) or just use more workers if it is appropriate for you.

If you have any questions feel free to ask.

**Comment by MaxDaten** [comment]
Hi and thanks for your fast reply.

> 2) What do you see on latency graphs? may be when you move to ec2 latencies grow. If one request takes 100ms for example you will not be able to generate more than 10 rps sending requests one after another. In this case you can either send them in parallel (see parallel option for loop) or just use more workers if it is appropriate for you.

Now it makes click on my side, of course, I didn't considered it.

![screenshot 2016-01-09 04 49 56](https://cloud.githubusercontent.com/assets/1087418/12214255/dbd05132-b68c-11e5-9a57-c1f148223dce.png)

So my latency is around 150ms, and this explains the ~ 60 rps

```
1000ms / 150ms = 6,6
6.6 * 10 [worker] = 66 [rps]
```

Thanks for bumping me into it. :)


> 1) Actually, both graphs look odd to me. If you run the script with default var values you should see a ramp from 10 to 100 (10x1 to 10x10) rps, but I see 250rps on your second graph. Look what I have on localhost for your script with default settings: 

Your are right, now I have the same graph. I can't recall what I may have done wrong, maybe I was too tired an picked a wrong screenshot. Sorry for the confusion.

Thanks for your help, I will close this issue.
