### ISSUE TITLE
Loop arguments get evaluated every iteration

### ISSUE THREAD

**Issue by lukyanov** [machinezone/mzbench#37]
Imagine I have the following scenario:

    {loop, [{time, {{calculate_loop_timeout}, sec}}], [
        {do_something}
    ]}

`calculate_loop_timeout` is a function defined in the worker module. I expect that this function will be called once, return a value and then this value will be used as an argument for the loop. What happens instead is that this function gets called every iteration of the loop. If the function is not deterministic (returns some random value, for example), then it will return a different value each iteration which will lead to an unpredictable behaviour of the scenario.

**Comment by timofey-barmin** [comment]
Hi Yurii glad to hear from you!

It works like this for a reason actually. For instance you may want to increase loop working time using this feature buy changing variable from our dashboard:

```
{loop, [{time, {{var, "working_time"}, sec}}], [
    {do_something}
]}
``` 
If you change "working_time" variable value in the dashboard it will affect the actual working time of the loop.

Not sure if it helps but in c++ for example it works the similar way:

```
for (int i = 0; i < f(); i++) {
    ...
}
```

f() will be called on every iteration.
