### ISSUE TITLE
Basic HTTP Worker Example

### ISSUE THREAD

**Issue by moigagoo** [machinezone/mzbench#38]
Please add a couple of example benchmarks for simple HTTP load testing.

If I want to test my service with ApacheBench, I just do `ab mysite.com`. If I want to do the same with mzbench, I have to read through the entire documentation and learn about workers and stuff, just to write a simple bench at the end.

**Comment by parsifal-47** [comment]
I forgot why do we have this issue opened,
simple HTTP load testing scenario creation is described here:
https://github.com/machinezone/mzbench/blob/master/doc/scenarios/tutorial.md

Please feel free to re-open this issue or create new one if needed,
thank you!
