### ISSUE TITLE
http worker: Add Support for Request Options

### ISSUE THREAD

**Issue by moigagoo** [machinezone/mzbench#39]
Currently, there's no way to do basic auth, which is sad.

Since mzbench uses hackney, and hackney supports it via `Options`, it'd be great to be able to pass options to hackney, e.g. with a `set_options` function.

**Comment by parsifal-47** [comment]
Added to master, please check if it works for you
https://github.com/machinezone/mzbench/commit/899f4f803d9f0c02a18e72010ca6c2cdb043f467

**Comment by moigagoo** [comment]
Unfortunately, I couldn't make it work.

I added `{set_options, [{basic_auth, {"admin", "password"}}]},` to my scenario and got this in logs:
```
pool1: line 13: Unknown function set_options/1.”]
```

Modifying *workers/http/src/http_worker.erl` doesn't do anything. The worker code seems to come from a different source.

**Comment by parsifal-47** [comment]
The problem is tuples, you couldn't have tuples in your code because MZBench is trying to execute them as functions, to fix this, you need to use "tuple" function "t", for example:

`{set_options, [{t, basic_auth, {t, "admin", "password"}}]},`

**Comment by moigagoo** [comment]
Thanks!
