### ISSUE TITLE
documentation to use worker

### ISSUE THREAD

**Issue by benoitc** [machinezone/mzbench#4]
There is a documentation to create a worker but nothing that explains how to use it. More generally how do we create custom nodes?

**Comment by parsifal-47** [comment]
A worker could be added to node with {make_install...} directive:
https://github.com/machinezone/mzbench/blob/master/doc/scenario_dsl.md#top-level-directives

After that, it should be additionally specified within {pool...} declaration:
https://github.com/machinezone/mzbench/blob/master/doc/scenario_dsl.md#the-pools

For example:
https://github.com/machinezone/mzbench/blob/master/workers/simple_http/examples/simple_http.erl

You are right, we don't have such guide and we should make it,
it is a good point, thanks!

**Comment by benoitc** [comment]
@parsifal-47 thanks for the links :) It helps a lot there. Hopefully I will be able to show some stuff soon.

**Comment by parsifal-47** [comment]
We have added a few words about cloud worker execution:
https://github.com/machinezone/mzbench/blob/master/doc/worker_howto.md#worker-execution
