### ISSUE TITLE
New metrics in runtime

### ISSUE THREAD

**Issue by MrAlone** [machinezone/mzbench#42]
Hi guys,
it would be great to have an opportunity to add new metrics in runtime or in special state when a worker can get information from somewhere (for example from scenario). Sometimes it needs to monitor metrics from different configurations of systems.

**Comment by parsifal-47** [comment]
Sorry for late answer, we currently working in this direction, as soon as we migrate off exometer -- we'll have this feature, we'll let you know

**Comment by timofey-barmin** [comment]
mzb_metrics:declare_metric is in master and can be used for metric declaration any time during the bench.

**Comment by MrAlone** [comment]
Thank you, guys)
