### ISSUE TITLE
Smallish confusion in defining statements

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#44]
Hi, I'd like to pass a proplist as an argument in a scenario file like this:

```
[
{pool, [{size, 500},
    {worker_type, mqtt_pub_worker}], [
  {connect, [{clean_session, true}, {client_id, random}] %% <- and more properties
}]}]
```

while only defining a connect function in the worker. Mzbench expects statement functions for clean_session, client_id etc here, there's no way around that, right?

**Comment by timofey-barmin** [comment]
Hi,

Yeah, in that case mzbench expects clean_session and client_id to be functions. But we have a workaround. You can use 't' function (t means tuple). It works like {t, element1, element2, ...} returns {element1, element2, ...}. In your case it would be {connect, [{t, clean_session, true}, {t, client_id, random}]}.

**Comment by ioolkos** [comment]
Love it. Thanks :)
