### ISSUE TITLE
Is the hdrhistogram resolution configurable?

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#46]
Example: can I make mzbench capture and graph the 99.99 percentile?

**Comment by timofey-barmin** [comment]
Hi,

No, right now it's not configurable and we have plans to implement it. We use hdr_histogram inside and it supports any percentiles so you can change the code a bit and get 99.99 percentile. Try to search for hdr_histogram:percentile(

**Comment by ioolkos** [comment]
I see, thanks Timofey!
