### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by aidylewis** [machinezone/mzbench#49]
I think, the link 'Simple HTTP worker example →' on [this page](http://machinezone.github.io/mzbench/workers/#how-to-write-a-worker) should [point here](https://github.com/machinezone/mzbench/blob/master/workers/simple_http/src/simple_http_worker.erl)
and [not here](http://machinezone.github.io/workers/simple_http/examples/simple_http.erl).

**Comment by parsifal-47** [comment]
Fixed,
Thanks a lot!
