### ISSUE TITLE
cloud provider plugin API

### ISSUE THREAD

**Issue by Licenser** [machinezone/mzbench#5]
Hi,
I'd be interested to add a cloud connector for project-fifo [1], but I am a bit confused about what exactly the functions are supposed to return. 

The spec reads:
```erlang
-spec create_cluster(Name :: string(), NumNodes :: pos_integer(), Config :: #{}) -> {ok, [string()], [string()]}.
```

and I suspect that to be ID's and IP's? where the ID is 'just a name' and the IP is well (an ip). argument `N` in the first list corresponds to argument `N` in the second?

However the function also returns a `UserName` in the tuple (having 3 entries) Would it be safe to default that to something like 'root' or 'admin' if those users are guaranteed to exist?

**Comment by merlin86** [comment]
Hi,

the spec seems to be slightly incorrect. This method should return a four-term tuple:

    {ok, ClusterID, UserName, HostList}

The different fields have the following meaning:

  * `ClusterID` - This term will be passed to `destroy_cluster/1` when the benchmarking system wants          to deallocate the compute nodes. It exact content is up to the plugin developer.
  * `UserName` - The benchmarking system will use this user name to ssh to the allocated compute nodes.
  * `HostList` - is the list of hostnames or IPs of allocated nodes.

Thank you for pointing out the incorrect spec and the lack in the documentation. We should probably write a "Cloud Plugin Developer Guide" or something like this.

I hope this helps!

**Comment by parsifal-47** [comment]
one more important detail:
hosts should be accessible for each other via hostnames, amazon does not provide such functionality by default and hostname->IP correspondence is set by mzb_api_ec2_plugin, check update_hostfiles/2 function for details and feel free to report any issues if something won't work. If hosts won't be accessible for each other you would see wait_cluster_start finished by timeout.

Thanks!

**Comment by Licenser** [comment]
Thanks a lot! I'll try to document the steps I take perhaps that will help as an base for a guide how to write connectors.

**Comment by parsifal-47** [comment]
Cloud plugin documentation became available at https://github.com/machinezone/mzbench/blob/master/doc/cloud_plugin.md
