### ISSUE TITLE
gitter client

### ISSUE THREAD

**Issue by aidylewis** [machinezone/mzbench#51]
Hi, 

My name is Adrian Lewis and I work for the BBC Digital Load Test Team. I am thinking of incorporating MZBench into our toolbox of load-tools but I may need to ask some questions . I wondered if you would consider using a gitter client for your project, so myself and other users could ask these questions? 

Many Thanks

**Comment by parsifal-47** [comment]
Hi,

Thanks for your interest, we have created dedicated gitter room, link in README.md and below:
https://gitter.im/machinezone/mzbench?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

feel free to ask any questions
