### ISSUE TITLE
Just released a MQTT worker for MZBench & VerneMQ

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#53]
thought I'd let you know: [https://github.com/erlio/vmq_mzbench](https://github.com/erlio/vmq_mzbench)

It's very very preliminary though :)
Thanks for your help lately!

**Comment by parsifal-47** [comment]
Thanks for using our software!
Please let us know if you have questions or issues

**Comment by timofey-barmin** [comment]
@ioolkos, that's super cool!

Thx for letting us know.

**Comment by avasenin** [comment]
Thx for letting us know. It's a pleasure to know that

**Comment by ioolkos** [comment]
Cheers, MZBench is awesome! :)
