### ISSUE TITLE
Variables in scenario DSL?

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#54]
within the sequential jobs of a pool especially.

what is the estimated effort to add this? is there a killer reason against it?

I tried to check if his has already been asked, sorry if it has.
Keep up the great work :)

**Comment by ethercrow** [comment]
Could you provide a motivating example? So far we've been very cautious with adding new features to the DSL. For examples, we've already rejected an idea of having conditionals in it, but instead discussed what was the underlying need for them and then satisfied that need in less invasive way.

**Comment by ioolkos** [comment]
I understand and share your caution in principle.

I'm looking for a way to do the following:
a) generate random ClientID's to connect with. (connect statement command)
b) then subscribing to an MQTT topic where the ClientID is part of the topic string (subscribe statement command)

Can I do this with a external resource file?

**Comment by ioolkos** [comment]
Just realized a combined connect_and_subscribe statement might be my way out (well.. still can't subscribe independently and later with that in the scenario, but it's probably enough to start with).

**Comment by timofey-barmin** [comment]
more solutions: If connect function returns

**Comment by ioolkos** [comment]
jep, thanks.
:+1:
