### ISSUE TITLE
Using self-compiled erlang does not work

### ISSUE THREAD

**Issue by larshesel** [machinezone/mzbench#57]
Hi, I ran into an issue where mzbench could not find my self-compiled erlang which is only available in my user PATH variable. Unfortunately the value of the user PATH variable is discarded due to the `source /etc/profile` here:
https://github.com/machinezone/mzbench/blob/master/common_apps/mzbench_utils/src/mzb_subprocess.erl#L21

I made a hack where I removed the `source /etc/profile` which makes it work on my system: 
https://github.com/larshesel/mzbench/commit/b9b40edcd9e3430b5f63fbcb15ecff175f83e04d

This is probably not the correct fix, and there's of course a good chance that maybe I'm just doing something wrong in the first place.

**Comment by ethercrow** [comment]
Can you try with `-l` option added to bash there (with `source /etc/profile` still deleted)? If that still works then we should consider changing from manually sourcing `/etc/profile` to relying on `bash -l` doing it by itself.

**Comment by larshesel** [comment]
The `-l` option works for me. Change the commit so it looks like this: https://github.com/larshesel/mzbench/commit/e1bc28425d6327823f89e1b0c21f56f610bb135c

**Comment by larshesel** [comment]
Hi @ethercrow, should I create a PR with the branch or do you think there are better ways at solving the issue?

**Comment by parsifal-47** [comment]
sorry for slow reaction, we have committed this patch directly to master so there is no need for PR, thanks a lot for your contribution, feel free to create any pull requests to MZBench!

**Comment by larshesel** [comment]
great - thanks a lot!
