### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by brucify** [machinezone/mzbench#59]
[Hex.pm](https://hex.pm) is the package manager for the Erlang ecosystem. Uploading to Hex.pm would allow people to more easily discover this project.

https://hex.pm/packages?search=bench

Use [Rebar3](http://www.rebar3.org/) to publish. See publishing guide on http://www.rebar3.org/docs/publishing-packages

**Comment by parsifal-47** [comment]
Thanks, we'll try to use it

**Comment by parsifal-47** [comment]
I've finally checked Hex.pm, looks like it couldn't host full applications like MZBench (since it is not a library). Other Erlang applications like rabbitmq are not published with it (only some internal libraries).

What do we need here is something like rpm or pypi
