### ISSUE TITLE
Problem viewing logs in web frontend

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#60]
Hi,
I just updated mzbench, and there's some minor trouble with logs in the webfrontend.
For new tests, I can't seem to see userlogs, and
for older tests, the frontend tries to load logs, but just tries forever.

Should I clear all logs somehow? What has changed exactly?

**Comment by merlin86** [comment]
Just run `<MZBENCH_DIR>/bin/migrations.py <Path your mz-bench data dir>` and restart the server, then everything should be all right. MZBench data dir is usually `~/.local/share/mzbench_api/data`

In general, you should always run migrations when you update the server.

**Comment by ioolkos** [comment]
Thank you very much for your quick helpful answer.
I hit some unicode errors during migration, but now just started with a fresh data dir.
