### ISSUE TITLE
Can't provision EC2 nodes due to this permission issue

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#61]
Hi,

This is not directly an MZBench issue... but maybe you guys have seen it?
What I want to do is to run the dashboard on my Laptop and connect to EC2 workers, but the provisioning fails with this kind of errors.

```
16:28:23.316 [error] [ API ] <0.10341.0> [ EXEC ] Command execution failed in 1931.868 ms
Cmd: ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ec2-52-some-IP.us-west-2.compute.amazonaws.com "source /etc/profile; mkdir -p /tmp/mz/bench-16-1462811172"
Exit code: 255
Output: Warning: Permanently added 'ec2-52-some-IP.us-west-2.compute.amazonaws.com,52.some.IP' (ECDSA) to the list of known hosts.
Permission denied (publickey).
```

Mind you, I'm kind of an Amazon newbie ;)

**Comment by parsifal-47** [comment]
Hi,
no problem :)
it means that you don't have right public key, which is set by {key_name, "<something>"} parameter at mzbench server configuration. This keys are managed with AWS -> EC2 -> Key Pairs at Web console, for example. You can add the key to server by putting it to ~/.ssh/id_rsa or (in case you already have something there) use ssh-add <key-name>

**Comment by ioolkos** [comment]
Awesome...

I added `IdentityFile path/to/your/amazonkey.pem` to `~/.ssh/config`, now this works.

Thanks, Renat! :+1:

**Comment by twonds** [comment]
This should be in the documentation.

**Comment by parsifal-47** [comment]
Thanks for comment, added to documentation: https://github.com/machinezone/mzbench/commit/17afdc829a80a4a1419ddc14db3e2cf2ef1c7b68
