### ISSUE TITLE
Looking for ways to dynamically configure the ami-3b90a80b image

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#62]
Hello, 
me again...
Had the idea to try some OS configuration on Amazon with a pre_hook script in my scenario files.
Should stuff like this work? (I tested, and it doesn't seem to increase file-max).

```
{pre_hook, [{exec, all, "sudo sysctl -w fs.file-max=100000"},
{exec, all, "sudo sysctl -e -p"}]},
```

Could I possibly reboot a system in a pre_hook?

**Comment by ioolkos** [comment]
My actual goal is to dynamically increase ulimit -n, which is set to 1024 per default.

**Comment by parsifal-47** [comment]
Hi,
this limit could be increased inside image, AMI is like a saved state of a system, you could create instance with this AMI, go to console, increase limit and make new AMI from instance. As I remember you need to edit /etc/security/limits.conf file to change this limits permanently, you need to add two lines

```
* soft nofile 16384
* hard nofile 16384
```
and relogin.

Also, we were planning to upgrade our MZBench AMI to erlang-18, we could increase limits with this upgrade, it won't be hard

**Comment by ioolkos** [comment]
Thanks :)
I didn't know I could make an AMI image based on an existing one. That's great. I'm trying to achieve at least 50k concurrent connections from a client machine, possibly even more, for distributed load testing. I'll try building an image.

But, of course, an official MZBench AMI with Erlang 18 would be awesome!

**Comment by parsifal-47** [comment]
We have published a set of images for every zone, ulimit on these images is 100000 and Erlang is now 18:

```
us-west-2       ami-ee8d718e
us-east-1       ami-61f11f0c
us-west-1       ami-fc28509c
eu-west-1       ami-4554c136
eu-central-1    ami-8d48a5e2
ap-northeast-1  ami-78a24419
ap-northeast-2  ami-ef579f81
ap-southeast-1  ami-66fd2b05
ap-southeast-2  ami-21634c42
sa-east-1       ami-7798101b

```

let me know if it works for you :)

**Comment by ioolkos** [comment]
That's great news! :)

I tested building my own snapshot with the old AMI (worked perfectly). I also tested the new `ami-ee8d718e` yesterday in a quick run. Worked! :+1:
