### ISSUE TITLE
value out of range error

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#63]
```
12:25:17.753 [error] <0.231.0> gen_fsm <0.231.0> in state connected terminated with reason: {value_out_of_range,-791} in mz_histogram:notify/2 line 71
12:25:17.774 [error] <0.231.0> CRASH REPORT Process <0.231.0> with 0 neighbours exited with reason: {value_out_of_range,-791} in mz_histogram:notify/2 line 71 in gen_fsm:terminate/7 line 626
```

Could this be caused by clock differences on amazon machines?

**Comment by parsifal-47** [comment]
depends on what you measure,
you could call something like:

`    _ = mzb_metrics:notify({"something", histogram}, -791)
`
and this issue reproduced,

it could be caused by time difference depending on worker code

**Comment by ioolkos** [comment]
Thanks, Renat. 
So the gen_fsm crashing here *does* stop metrics collection, or affect my metrics, right?

**Comment by parsifal-47** [comment]
It shouldn't affect metrics collection, it crashes only caller process

**Comment by ioolkos** [comment]
Okay, I see.
Thanks & enjoy your weekend!
