### ISSUE TITLE
How test a custom worker

### ISSUE THREAD

**Issue by nkrode** [machinezone/mzbench#66]
I'm following the tutorial to write a custom worker http://machinezone.github.io/mzbench/workers/#how-to-write-a-worker, I created a new worker using tcp template using the command:
`bin/mzbench new_worker --template tcp pingpong`

To test this, I ran:
`bin/mzbench run_local pingpong/examples/pingpong.erl`

However, I'm getting an error:
pool1: Couldn't get module info for pingpong_worker
pool2: Couldn't get module info for pingpong_worker

I assume I'm missing the make_install command in pingpong/examples/pingpong.erl. However I'm not sure how to reference it to a local dir where my test worker is create (./pingpong) instead of a git repo:
{make_install, [{git, "<URL>"}, {branch, "<Branch>"}, {dir, "<Dir>"}]}

**Comment by parsifal-47** [comment]
Hi,
you don't need make_install directive for run_local, but you need to run it from a worker folder so mzbench scripts could build and include necessary binaries from worker

it means in your case:
`cd pingpong; ../bin/mzbench run_local example/pingpong.erl`

you need make_install when you run it in non-local mode, error message is not really informative, sorry for that and thanks for your interest, feel free to ask any additional questions

**Comment by parsifal-47** [comment]
Does my advise work for you?

If you have more questions don't hesitate to ask

**Comment by nkrode** [comment]
+1 it worked, thanks
