### ISSUE TITLE
Web UI not showing

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#67]
Hello,

I just noticed that for a fresh clone of MZBench, the UI at localhost:4800 only shows the Navigation Bar with "MZBench, Docs and Issues". 

Haven't investigated further, but what could be the reason for that? 

Thanks :)

**Comment by merlin86** [comment]
This means that the JavaScript code can't execute for some reason.

The possible reason is that you don't have the internet connection, we load some resources from CDN.

But you should look at the developer console of you browser to see what happens.

Regards

**Comment by ioolkos** [comment]
Thanks for your answer @merlin86 

Seems like Cowboy doesn't serve the js and css files for me?


![loadmz](https://cloud.githubusercontent.com/assets/282359/16357287/afe4937c-3af2-11e6-9f1a-6951479923fe.png)

**Comment by ioolkos** [comment]
Seems I found the reason, I inadvertently compiled MZBench with an OTP 18.3.4 patch version. 
Compiles, but doesn't run apparently.

All systems good now. Thanks for your help, enjoy your weekend, Vadim! :)

**Comment by ioolkos** [comment]
I still have Javascript troubles. Clicking any UI element does select the right path in the URL, but doesn't actually load.

![loadmz2](https://cloud.githubusercontent.com/assets/282359/16357431/b93409c2-3af6-11e6-8743-74fce53d3498.png)

**Comment by merlin86** [comment]
Yes, the JS is actually not working anymore, but it is totally weird. The errors are originating in the file that was last modified the 8 of October 2015.

Investigating. Thanks for reporting.

**Comment by parsifal-47** [comment]
please try updated master and let us know if it works for you

**Comment by ioolkos** [comment]
Looks like this fixes the UI issues for me, yes.

Thanks for your effort & responsiveness! :)

**Comment by ioolkos** [comment]
Looks like the same WebUI error is back on a fresh clone?
is this something I can fix locally? (ie Browser/Javascript etc?)

**Comment by parsifal-47** [comment]
I have checked the latest master in chrome and safari, it works, maybe there is some inconsistency in JS or server crashes.

What actually do you see? Just a head bar or there are two blue "loading" bars below? Is there a red bar at the top right corner?
If red bar appears it means that your server has crashed on start for some reason, you need to check logs. If you don't see blue "loading" bars it looks like js code issue.

You could also cleanup server release to remove some stuff from previous builds (normally you don't need to do that but just in case). To do that, `rm -rf server/_build/default/rel`

**Comment by ioolkos** [comment]
Thanks for your answer @parsifal-47 

I don't see the blue loading bars or the red bar at the top right.

Only a grey stripe with "MZBench Docs Issues". It's the same Javascript error as before (Internal Server Error 500 for the css and javascript ressources).

Tested in Chrome and Firefox.
This is with a complete fresh clone & build.
Some dependency hackery by  @merlin86 fixed this the last time, don't know why it's back.

**Comment by ioolkos** [comment]
Basically, I get a stacktrace like this for every JS file:

> 10:41:49.295 [error] emulator Error in process <0.1040.0> on node mzbench_api@capo with exit value:
{[{reason,undef},{mfa,{cowboy_static,init,2}},{stacktrace,[{erlang,nif_error,[undef],[]},{binary,split,3,[{file,"binary.erl"},{line,218}]},{filename,unix_splitb,1,[{file,"filename.erl"},{line,652}]},{cowboy_static,fullpath,1,[{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/cowboy/src/cowboy_static.erl"},{line,94}]},{cowboy_static,init_dir,3,[{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/cowboy/src/cowboy_static.erl"},{line,82}]},{cowboy_handler,execute,2,[{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/cowboy/src/cowboy_handler.erl"},{line,39}]},{cowboy_protocol,execute,4,[{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/cowboy/src/cowboy_protocol.erl"},{line,462}]}]},{req,[{socket,#Port<0.4136>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.1040.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},39448}},{host,<<"localhost">>},{host_info,undefined},{port,4800},{path,<<"/js/vendors/bootstrap-notify.min.js">>},{path_info,[<<"bootstrap-notify.min.js">>]},{qs,<<>>},{bindings,[]},{headers,[{<<"host">>,<<"localhost:4800">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0">>},{<<"accept">>,<<"*/*">>},{<<"accept-language">>,<<"en-US,en;q=0.5">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"referer">>,<<"http://localhost:4800/">>},{<<"cookie">>,<<"sessionid=xwmc8e72ndrthfa6xmbw2qz1mzobkeud; csrftoken=6uSyIWQGpKtV2xoHCkhYQQbTc4K1HeUB; grafana_sess=f1d5b47bef4e621c">>},{<<"connection">>,<<"keep-alive">>}]},{meta,[]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,{priv_dir,mzbench_api,["/http_root/js/vendors"],[{mimetypes,cow_mimetypes,web}]}}],[{cowboy_protocol,execute,4,[{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/cowboy/src/cowboy_protocol.erl"},{line,462}]}]}

**Comment by timofey-barmin** [comment]
Hi

Which erlang version do you use?

**Comment by ioolkos** [comment]
Boom! :) 
this got me before. was on a otp patch version.
A recompile will certainly solve this problem.

Thank you, Timofey!
