### ISSUE TITLE
Deterministic ClientIDs in a pool

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#69]
Hello,

I just wondered what would be the best way to have a non-random, deterministic ID created for a worker pool. This could be as simple as just a counter.

How would you go about this? Let's say you have a pool with 10k workers, a connect function (that needs to  give a client ID) and you want the IDs to be named "1" to "10000".

**Comment by timofey-barmin** [comment]
You can use worker id I I suppose. Get it from Meta which is passed to every worker function.

```
    ID = proplists:get_value(worker_id, Meta)
```

I'm not sure what the first Id is 0 or 1. But you can easily check it.

**Comment by ioolkos** [comment]
Ah, when it's that simple and you get offered the solution on a silver tablet! :)
Thanks a lot!
