### ISSUE TITLE
Upper pool size limit?

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#70]
Is there an upper limit for a single pool size?
if not, is it bound by something?

I just tried to simplify a test by merging a couple pools and increasing the pool size. But one pool only seems to give me 12500.

Might be doing something wrong, of course.

Thanks :)

**Comment by parsifal-47** [comment]
It is limited by number of processes on Erlang VM, I have started pools with millions of workers, you could change this limit by setting vm_args=+P 1000000, for example. By default, process number is not 12k, it is too low, what error message do you get when you try to start more than 12k?

**Comment by ioolkos** [comment]
How does it feel to start millions of workers?! 
(I'll know soon :)

OK, have a laugh at me: Don't wait for a signal that never arrives. Problem solved.
Thanks again, gentlemen.
