### ISSUE TITLE
"bad_hdr_binary"

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#71]
> 11:03:27.239 [error] [ API ] <0.3224.0> Stage 'pipeline - running': failed
Benchmark has failed on running with reason:
badarg

> Stacktrace: [{hdr_histogram,from_binary,[{error,bad_hdr_binary}],[]},
             {mzb_api_bench,'-aggregate_results/3-fun-4-',4,
                            [{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_bench.erl"},
                             {line,943}]},
             {lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},
             {mzb_api_bench,aggregate_results,3,
                            [{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_bench.erl"},
                             {line,925}]},
             {mzb_api_bench,handle_stage,3,
                            [{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_bench.erl"},
                             {line,293}]},
             {mzb_pipeline,'-handle_cast/2-fun-0-',6,
                           [{file,"/home/afa/Erlang/machinezone/mzbench/server/_build/default/deps/mzbench_api/src/mzb_pipeline.erl"},
                            {line,172}]}]

Seen with a simple test run. Is it just me? ;)
The actual test runs through, this error shows basically at test end.

**Comment by timofey-barmin** [comment]
Yep, that must be a bug in hdr_histograms. We've already pushed a fix. Try to run on latest master please.

**Comment by ioolkos** [comment]
Great, thanks Timofey! :)
