### ISSUE TITLE
add a way to pass application config in scripts

### ISSUE THREAD

**Issue by benoitc** [machinezone/mzbench#73]
It can be useful sometimes to be able to pass application config environment in the script file, to initialize some data for all workers. Right now I'm using sys.config for it, but having it in the script file would allow any user to simply ship their script file.

**Comment by parsifal-47** [comment]
Just in case, we have a way to set up some variables and change them even in runtime, for example

https://github.com/machinezone/mzbench/blob/master/acceptance_tests/scripts/vars_defaults.erl

how to change in runtime

https://github.com/machinezone/mzbench/blob/master/doc/cli.md#change_env

or from a dashboard

**Comment by benoitc** [comment]
Forgot to answer, sorry. The current way to do it is ok for my current purpose. Thanks for the links!
