### ISSUE TITLE
mzb_staticcloud_plugin

### ISSUE THREAD

**Issue by benoitc** [machinezone/mzbench#74]
is there any documentation on how to use this plugin? more specifically how to deploy the nodes?

**Comment by parsifal-47** [comment]
There is a short description here:
https://github.com/machinezone/mzbench/blob/master/doc/cloud_plugins.md#static-cloud

if you need something more -- please ask and we add this information to documentation

thanks for your interest!

**Comment by benoitc** [comment]
Thanks I have it working :)
