### ISSUE TITLE
no run server

### ISSUE THREAD

**Issue by edgiru** [machinezone/mzbench#77]
edgi@ubuntu:~$ cd mzbench
edgi@ubuntu:~/mzbench$ ./bin/mzbench start_server
Executing make -C /home/edgi/mzbench/bin/../server generate
....................................................
Executing /home/edgi/mzbench/bin/../server/_build/default/rel/mzbench_api/bin/mzbench_api start
..........................................................................................................................           ..........................................................................................................................           ..........................................................................................................................           ..........................................................................................................................           ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... ....................

**Comment by timofey-barmin** [comment]
Hi Aduard,

That looks odd. Actually we are working on more informative start_server command currently. So it's going to be easier to understand what's happing there once we finish.
Until then could you please check the server errors logs here server/log/error.log ?
Also you can try visit http://localhost:4800 to check if the server is actually started. Maybe it's simply the start command hangs.
Monitoring `ps aux | grep beam` also usually helps.

**Comment by edgiru** [comment]
Hello! I apologize, I'm to blame, it was necessary to run with full rights. sudo ./bin/mzbench start_server
