### ISSUE TITLE
mzb_watchdog timeout

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#78]
Fresh clone of MZBench, compiled in Erlang 18.3. I see this in the user log (the system log doesn't show errors):

>17:50:22.432 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
17:50:22.639 [info] <0.7.0> Application mqtt_worker started on node 'mzb_director1168_0@127.0.0.1'
17:51:42.757 [error] <0.178.0> gen_server mzb_watchdog terminated with reason: {timeout,{gen_server,call,[mzb_interconnect,{call_director,is_director_alive},30000]}} in gen_server:call/3 line 212
17:51:54.253 [error] <0.195.0> gen_server mzb_time terminated with reason: {timeout,{gen_server,call,[mzb_interconnect,get_director]}} in gen_server:call/2 line 204
17:52:36.512 [error] <0.216.0> gen_server <0.216.0> terminated with reason: no try clause matching {{error,{timeout,{gen_server,call,[mzb_metrics,get_metrics]}}}} in mzb_management_tcp_protocol:dispatch/2 line 33

I can't reliably run my tests. I'm not sure how to investigate this error.
Any ideas what could be happening here?

**Comment by parsifal-47** [comment]
Probably, connection between nodes got lost for some reason, I'm not sure why it is in user space. Do you have connectivity between benchmarking nodes and director on ports 4801, 4802 and 4803? (these numbers are configurable, so maybe you changed them)

**Comment by ioolkos** [comment]
OK, thanks @parsifal-47!
I didn't change the 48xx ports.
This is for a local dummy test, not EC2. 
One thing: I always use the same server.config file, maybe you have changed something in the config that could matter here?

I'll try to find out more today. Thanks again.

**Comment by ioolkos** [comment]
I think I have resolved this by a combination of re-compiling & not using existing server.config file.
