### ISSUE TITLE
Error while provisioning

### ISSUE THREAD

**Issue by larshesel** [machinezone/mzbench#80]
Sorry for spamming you with issues, but I'm stuck on another issue when trying to run a test. Does this mean anything to you? I'm running on master from today and erlang 18.

``` erlang
15:26:07.323 [error] [ API ] <0.329.0> Stage 'pipeline - provisioning': failed
Benchmark has failed on provisioning with reason:
{badmatch,{error,exdev}}

Stacktrace: [{mzb_api_provision,download_file,5,
                 [{file,
                      "/home/lhc/dev/erl.io/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_provision.erl"},
                  {line,211}]},
             {mzb_api_provision,'-install_package/6-fun-0-',9,
                 [{file,
                      "/home/lhc/dev/erl.io/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_provision.erl"},
                  {line,255}]},
             {mzb_lists,'-pmap/2-fun-0-',4,
                 [{file,
                      "/home/lhc/dev/erl.io/mzbench/server/_build/default/deps/mzbench_utils/src/mzb_lists.erl"},
                  {line,35}]}]
```

**Comment by timofey-barmin** [comment]
Hi,
hm, looks like it happens when we try to move a file from /tmp somewhere else. Apparently these two places are located on different filesystems and file:rename() returns {error, exdev} in that case. That's weird because manual says that the function could be used for moving files but it doesn't say what to do in case of different filesystems. I'm working on a solution for the problem.

**Comment by timofey-barmin** [comment]
Please try tbarmin/fix-rename-issue branch

**Comment by larshesel** [comment]
Thanks, I'll give that a go either later today or tomorrow!

**Comment by larshesel** [comment]
Using that branch I got everything working!

One thing that puzzled me a bit - if I only opened ports 4801&4802 I got some cluster communication errors (see below) which indicated some kind of connectivity issue  - so  I opened the range 4800-5000 to be accessible from everywhere and then it worked.

Thanks again for helping out!

```erlang
11:34:22.771 [error] [ API ] <0.489.0> Stage 'pipeline - connect_nodes': failed
Benchmark has failed on connect_nodes with reason:
{connect_cluster_error,timeout}

Stacktrace: [{mzb_api_bench,handle_stage,3,
                            [{file,"/home/lhc/dev/erl.io/mzbench/server/_build/default/deps/mzbench_api/src/mzb_api_bench.erl"},
                             {line,223}]},
             {mzb_pipeline,'-handle_cast/2-fun-0-',6,
                           [{file,"/home/lhc/dev/erl.io/mzbench/server/_build/default/deps/mzbench_api/src/mzb_pipeline.erl"},
                            {line,172}]}]
```

**Comment by parsifal-47** [comment]
it shouldn't use that much ports, but two ports is not enough. It should be three of them, you could find numbers in config server/src/mzbench_api.app.src.script:

```
        {node_log_port, 4801},
        {node_log_user_port, 4802},
        {node_management_port, 4803},
```

**Comment by larshesel** [comment]
okay, that explains it I think, over here it says only to open the ports for SSH, 4801 and 4802: https://machinezone.github.io/mzbench/cloud_plugins/

**Comment by parsifal-47** [comment]
sorry, fixed

**Comment by parsifal-47** [comment]
I forgot to mention "node interconnect port", so the right port range is 4801-4804

**Comment by parsifal-47** [comment]
feel free to reopen this issue any time
