### ISSUE TITLE
Bad example of config in home directory of user.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#84]
When i compiles mzbench, it generates template of config which placed in ~/.config/server.config.example

So i found this template doesn't contains pair {mzbench_api, _ }.

It starts from:
```
[{keyfile,"~/.local/share/mzbench_api/server.key"},
 {metric_update_interval_ms,10000},
```

but should be:
```
[{mzbench_api, 
[{keyfile,"~/.local/share/mzbench_api/server.key"},
 {metric_update_interval_ms,10000},
...
}
```

Please fix it.

**Comment by parsifal-47** [comment]
Thanks a lot for reporting this!
Fixed: https://github.com/machinezone/mzbench/commit/f00715b490ee7240b0ec378e5423b650177808bd
