### ISSUE TITLE
node_rsync option is not described in documentation.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#85]
Hi.

I found this code:
https://github.com/machinezone/mzbench/blob/3e5a35f21f0c30509f07379504332c13cd067aeb/server/src/mzb_api_bench.erl#L556

so i think it is very useful option, and it must be described in documentation.

Thanks.

**Comment by parsifal-47** [comment]
fixed: https://github.com/machinezone/mzbench/commit/2011e866466853b9140e6858dbc4d8f9a3757668

Thank you!

**Comment by loguntsov** [comment]
When it will be available on https://machinezone.github.io/mzbench/deployment ?

**Comment by parsifal-47** [comment]
updated

**Comment by parsifal-47** [comment]
closing, feel free to re-open if something more needs to be done here
