### ISSUE TITLE
Crash when files was placed on different file systems

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#86]
I found this line:
https://github.com/machinezone/mzbench/blob/3e5a35f21f0c30509f07379504332c13cd067aeb/server/src/mzb_api_provision.erl#L210
can cause crash when TmpFile and ToFile specify files on different file systems.

So i made patch for that: https://github.com/loguntsov/mzbench/commit/2fda969044ab50de7d6a2b8c8cb5b440fb7c53cd

**Comment by timofey-barmin** [comment]
Should be fixed in master. Please, check it out.
