### ISSUE TITLE
Deploy newest code of worker inside node.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#87]
I develop worker for mzbench with some scenarios.

The scenario has command make_install which allow get sources for worker and apply custom command inside this scenario. It allow use git to get sources.
But. It is not very useful for tests.
Yes, i know about local_run, but i want to see all graphs and other info inside html page, but not inside console log.
So i should make commit into git every time when i need test.

I think it will be very useful,if you will develop rsync method to get sources of worker.

How i can help with this thing ?

**Comment by loguntsov** [comment]
By the way, i found some code for rsync install.
Could you make description for that ?

**Comment by parsifal-47** [comment]
sorry for not describing this, you could check our acceptance tests:
https://github.com/machinezone/mzbench/blob/master/acceptance_tests/scripts/worker_from_rsync.erl
or
https://github.com/machinezone/mzbench/blob/master/acceptance_tests/scripts.bdl/worker_from_rsync.bdl

and we'll describe it soon, probably tomorrow

**Comment by parsifal-47** [comment]
fixed: https://github.com/machinezone/mzbench/commit/8aed4665977b0d3372eeb200fa0f9b19d5cf42dd
