### ISSUE TITLE
[Feature]: Gets metrics from server side.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#89]
We have way to get metrics from node side (test clients).
I think it will be very very useful if mzbench will allow gets metrics from server side (tested system).

I don't know how this basic implementation can look like. May do you have your ideas about that ?

**Comment by parsifal-47** [comment]
Currently, you could use API to get metric values during bench run (https://github.com/machinezone/mzbench/blob/master/doc/api.md#get-dataidnumber), in this case, you need to know bench id which could be sent by test scenario to system under test.

I understand that it is not straight way, but it could solve this problem

**Comment by loguntsov** [comment]
No, you didn't got me. I want get metrics from tested system.
So right now shema of interaction is:

mzbench_api -> nodes -> tested system.

So mzbench_api gets metrics from node, and shows/saves them into mabench_api host.
I want to implement way, to get metrics (and aggregate them, if it is needed) from tested system, and show/save them to mzbench_api. 

It can be killer feature too. 

Because right now, i can get my metrics from tested system, but they will be placed in my server, and will be not associated with concrete benchmark.

**Comment by ethercrow** [comment]
> I want to implement way, to get metrics (and aggregate them, if it is needed) from tested system, and show/save them to mzbench_api.

You can do that as a worker. Basically, your test scenario would contain a pool of some load generating workers and a pool of (probably just one) metric retrieving worker, that uses whatever metric API your service exposes and relays them to mzbench director using existing protocol.

**Comment by loguntsov** [comment]
mm i see your idea is good. thank you very much. :)
you can post your this idea in documentation, i think it can help other developers use mzbench more easy.

By the way, if compare mzbench with tsung, my choice is mzbench. Tsung is old solution with strange api and not good solutions inside code.

**Comment by parsifal-47** [comment]
Added a note on metric importing:
https://github.com/machinezone/mzbench/blob/master/doc/workers.md#importing-external-metrics

but it is not very specific because it depends on data source you have, we currently have an example only for statsd

**Comment by loguntsov** [comment]
Thanks, for that. 
Yes i already developed my own metric receive, it is very userful :)
Tsung don't allow make like that.
