### ISSUE TITLE
make_install (rsync) doesn't work as expected.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#90]
Hi.

I'm using make_install with rsync in my scenario.
When i run scenario on local machine, it works fine.
My worker was copied to temp folder, compiled and ran.
But when i tried to run scenario on remote machine, i got this issue:

```
08:07:09.496 [error] [ API ] <0.460.0> [ REMOTE EXEC ] Command execution failed:
Cmd: ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no sloguntsov@IP "source /etc/profile; mkdir -p /tmp/bench_mzbench_api_big-comp_1477_728427_249578 && cd /tmp/bench_mzbench_api_big-comp_1477_728427_249578 && rsync -aW  <PATH> deployment_code && cd deployment_code/ && make generate_tgz && mv *.tgz /tmp/bench_mzbench_api_big-comp_1477_728427_249512.tgz "
Exit code: 23

rsync: change_dir "<PATH>" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
```

So it tries find my sources in local folder of node, but i thought that it should copy sources from remote host where mzbench_api started.

Could you comment my issue ?

**Comment by parsifal-47** [comment]
it is expected behavior, usually packages are cloned and built on worker nodes because they could have incompartible operation systems. You could have different linuxes for example. For architecture-independent workers we have ability to build them on API server (because in some cases your workers could be isolated from source code base). But we don't have such option for rsync and probably in your case it is not arch-independent code. So if we implement this it would break if a code from api server couldn't run on workers

**Comment by loguntsov** [comment]
So you have inconsistent logic for make_install. Because when you uses git, it will get sources from remote machine, and you don't need place sources inside node. But when you uses rsync, you said i MUST place sources inside node. But it is killer feature to spread sources from host. 
Also allow of my script decide about architecture of node machine. But right now you force me spread sources manually or via git. Think it is not good thing.

**Comment by loguntsov** [comment]
So right now i forces to use git to get my sources, but i want use rsync as main method of spreading of sources. May you can make some flag to make logic as i ask?

**Comment by ethercrow** [comment]
@loguntsov: could you show your `make_install` statement with rsync? My guess is you have a local directory there, so it works on your machine but not on remote one.

If that's the case and your machine is accessible from remote one, you could change the rsync argument into something like `user@host_that_has_sources:/path/to/sources/`.

**Comment by loguntsov** [comment]
```
make_install(
  rsync = var("worker_path")
)
```

and i uses Makefile with this command:
```
	./lib/mzbench/bin/mzbench run --nodes=1 examples/oncam_followers_wait.bdl \
	    --env=worker_path=`pwd`/ 
```

so it replaced of current directory (root of worker) where Makefile running.

I got your idea, but it is not good solution, because all nodes should have access to my host system.
But i think it should be conversely, my host system should have access to all nodes via ssh.
It is like security hole.

**Comment by loguntsov** [comment]
> But i think it should be conversely, my host system should have access to all nodes via ssh.
and it already has this access.

**Comment by loguntsov** [comment]
By the way, why you uses rsync ? It is like local copy of files. You can use cp :)

**Comment by ethercrow** [comment]
It's easier to use rsync than to remember cp's flags for copying only what changed.

**Comment by loguntsov** [comment]
So what about normal solution of my request ? what we should fix or develop for that ?

**Comment by parsifal-47** [comment]
in your case it looks like you specified rsync address like a local one,
with git you could do the same and clone your local repo:
```
git clone mzbench mzbench2
```
this means clone mzbench to mzbench2, but if you specify something like:
```
git clone https://github.com/machinezone/mzbench mzbench2
```
the source is remote, the same with rsync, if you specify:
```
rsync local1 local2
```
it is like `cp` command, but if you specify
```
user@host_that_has_sources:/path/to/sources/ local2
```
it is remote.
Looks like in your case you need to add host and username, followed by the colon: `user@host:path`

I hope that my answer will help

**Comment by loguntsov** [comment]
No, you don't get my question. I understood your idea earlier.

I see that rsync running inside context of node, but it should be running inside context of host and should use ssh internally to pass sources from host to node. Because main purpose is spreading sources from host to node. Because it is good solution, when your system delivers files into empty node.

**Comment by parsifal-47** [comment]
yes, looks like I don't understand concept of EMPTY node, but behaviors of `rsync` and `git` are the same, the main difference in provision code is the command to call `git clone` or `rsync -aW`:
```
    CloneAndCDCommand = case InstallSpec of
        #git_install_spec{repo = GitRepo, branch = GitBranch, dir = GitSubDir} ->
            mzb_string:format("git clone ~s deployment_code && cd deployment_code && git checkout ~s && cd ./~s", [GitRepo, GitBranch, GitSubDir]);
        #rsync_install_spec{remote = Remote, excludes = Excludes, dir = SubDir} ->
            mzb_string:format("rsync -aW ~s ~s deployment_code && cd deployment_code/~s",
                [string:join(["--exclude=" ++ E || E <- Excludes], " "), Remote, SubDir])
    end,
```

all remote stuff remains remote and all local remains local

**Comment by loguntsov** [comment]
As i said above, if i will use user@host:/ address to get my sources from host it will be like security hole. I don't want open my machine for worker's node, and my machine is just local, it have no direct access to internet (NAT access).

This machine has access for each node, so why we should have not right way to get sources ?
why host machine can't send all sources to all nodes himself ? Why it should be from node side ?

The main purpose of my request is:
node shouldn't contains any specific code or something else. So i can clone one image of machine for all nodes.

**Comment by parsifal-47** [comment]
your point makes sense,
as far as I remember the idea behind current implementation, it was faster to fetch sources from multiple hosts simultaneously then fetching from api_server and then pushing to nodes. But maybe it is time to reconsider this approach, let's keep this issue open for now

**Comment by loguntsov** [comment]
Ok.
I think it is not big problem for host to make ssh connections for several nodes at same time :)

**Comment by loguntsov** [comment]
I made some patch which allow run rsync from host node.
Pls review it.

**Comment by parsifal-47** [comment]
closing ticket, feel free to reopen if needed
