### ISSUE TITLE
0.5.0 - Logs Tab Not Rendering Properly

### ISSUE THREAD

**Issue by pulltab** [machinezone/mzbench#96]
Hello. 

I am evaluating version 0.5.0, however, I am experiencing the following UI issue:

[Logs UI Error.pdf](https://github.com/machinezone/mzbench/files/718028/Logs.UI.Error.pdf)

It seems the UI is hitting an endpoint which is no longer supported?   Is there an additional step required of the user to retrieve the logs?

**Comment by timofey-barmin** [comment]
Hello John,

It looks like "old dashboard" is trying to connect to "new server". Probably javascript dashboard bundle is cached by the browser. Could you please try refresh the page without using cache (it is Shift+Command+R for chrome on mac). Or try different browser. 

I know we need to fix it.

**Comment by pulltab** [comment]
Sure, enough.

Thanks.
