### ISSUE TITLE
dynamic deadlock detection

### ISSUE THREAD

**Issue by ioolkos** [machinezone/mzbench#99]
Hello good folks of MZBench! :)

we run into a dynamic deadlock situation that I don't really understand. I want to wait for workers to be connected, before I start doing other stuff like this:

`set_signal(connect1, 1)`
`wait_signal(connect1, numvar("pool_size"))`

Now, depending on the numvar "pool_size", I run into dynamic deadlock detection.

Example:
If the poolsize is 5000, waiting for 5000 signals triggers deadlock detection.
If the poolsize is 5000, waiting for 2000 signals only, all works fine.

There is a related issue here: 
https://github.com/erlio/vmq_mzbench/issues/5

I seem to be missing something quite basic, I suspect.

**Comment by parsifal-47** [comment]
Hi!
dynamic deadlock means that you have some threads waiting for signals and no other threads running. In your case it could be if some threads have failed to connect and got crashed.

There is a metric "blocked.workers" inside "Errors and blocked workers" in "MZBench internals", and also "Worker status" at the same section if all running workers are blocked it is "dynamic deadlock". Please check if it is your case.

**Comment by ioolkos** [comment]
Thanks, @parsifal-47 
that's in fact what I see, yes. All started workers are also blocked. What's weird is that this happens independently of worker setup rate and overall number of connections. It just seems to detect deadlock after about 10 seconds into the test.

Are there any hardcoded timeouts of something I can configure? Thanks again for your time, Renat.

**Comment by parsifal-47** [comment]
yes, 10s is metric aggregation time, could be configured in server config 
`{metric_update_interval_ms, 10000}`. This parameter if changed, will affect the whole metric subsystem, so I suggest to put `wait` somewhere particular. But this shouldn't affect dynamic deadlock detection. So probably I didn't get your question, please let me know if my answer helps

**Comment by ioolkos** [comment]
Allright, the thing seems to be this: 
If I start a test, I have to make sure all my workers are started within < `metric_update_interval_ms`. 
If the first metric_update happens, and I'm still starting workers, there's a dynamic deadlock.

This is probably not expected behaviour, or is it?

**Comment by ioolkos** [comment]
Found a workaround https://github.com/erlio/vmq_mzbench/issues/5
Thanks for your time and help!

**Comment by parsifal-47** [comment]
anyway, it is something which should be fixed, it couldn't be a deadlock until all workers stared
